name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-10.15

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Cocoapods install
      uses: maierj/fastlane-action@v1.4.0
      with:
        lane: run cocoapods
        bundle-install-path: 'vendor'

    - name: Test
      uses: maierj/fastlane-action@v1.4.0
      with:
        lane: test
        bundle-install-path: 'vendor'
