name: Release

on:
  release:
    types: [published]

jobs:
  publish-binaries:
    runs-on: macos-10.15

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Ruby setup
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6

    - name: Bundle cache
      uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-
    - name: Bundle install
      run: |
        gem install bundler
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3

    - name: Cocoapods cache
      uses: actions/cache@v2
      with:
        path: Pods
        key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-pods-
    - name: Cocoapods install
      run: |
        bundle exec fastlane run cocoapods

    - name: Archive
      run: |
        ./scripts/archive.sh

    - name: Publish binaries
      uses: skx/github-action-publish-binaries@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: 'build/output/*.zip'
